# Generated by Django 5.1.4 on 2026-01-23 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('employee_id', models.CharField(max_length=20, verbose_name='รหัสพนักงาน')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('prefix', models.CharField(choices=[('mr', 'นาย/Mr.'), ('mrs', 'นาง/Mrs.'), ('miss', 'นางสาว/Miss'), ('dr_m', 'น.สพ./Dr.'), ('dr_f', 'สพ.ญ./Dr.'), ('other', 'อื่นๆ')], max_length=20, verbose_name='คำนำหน้าชื่อ')),
                ('prefix_other', models.CharField(blank=True, max_length=100, null=True, verbose_name='คำนำหน้าชื่อ (อื่นๆ)')),
                ('name_th', models.CharField(max_length=150, verbose_name='ชื่อ-สกุลภาษาไทย')),
                ('name_en', models.CharField(max_length=150, verbose_name='ชื่อ-สกุลภาษาอังกฤษ')),
                ('department', models.CharField(choices=[('IT', 'IT'), ('FIN', 'FIN')], max_length=50, verbose_name='แผนก')),
                ('position', models.CharField(choices=[('Manager', 'ผู้จัดการ'), ('Deputy Manager', 'รองผู้จัดการ')], max_length=100, verbose_name='ตำแหน่ง')),
                ('access_level', models.CharField(choices=[('read', 'Read Only (ดูอย่างเดียว)'), ('editor', 'Editor (แก้ไขข้อมูลได้)'), ('admin', 'Admin (ผู้ดูแลระบบ)')], default='read', max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager_comment', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to=settings.AUTH_USER_MODEL)),
                ('systems', models.ManyToManyField(to='access_requests.system')),
            ],
        ),
    ]
