# Generated by Django 5.1.4 on 2026-01-24 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='แผนก (Old)'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ตำแหน่ง (Old)'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='department_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_requests.department', verbose_name='แผนก'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='position_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_requests.position', verbose_name='ตำแหน่ง'),
        ),
    ]
