# Generated by Django 5.1.4 on 2026-01-24 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_requests', '0002_department_position_alter_accessrequest_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessrequest',
            name='department',
        ),
        migrations.RemoveField(
            model_name='accessrequest',
            name='position',
        ),
    ]
