# Generated by Django 5.1.4 on 2026-01-24 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_requests', '0003_remove_accessrequest_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessrequest',
            name='department_new',
        ),
        migrations.RemoveField(
            model_name='accessrequest',
            name='position_new',
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_requests.department', verbose_name='แผนก'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_requests.position', verbose_name='ตำแหน่ง'),
        ),
    ]
