# Generated by Django 5.1.4 on 2026-01-24 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_requests', '0004_remove_accessrequest_department_new_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='it_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='it_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_approvals', to=settings.AUTH_USER_MODEL, verbose_name='ผู้อนุมัติ (IT)'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='manager_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='manager_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_approvals', to=settings.AUTH_USER_MODEL, verbose_name='ผู้อนุมัติ (Manager)'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='reject_reason',
            field=models.TextField(blank=True, null=True, verbose_name='เหตุผลที่ปฏิเสธ'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='manager_comment',
            field=models.TextField(blank=True, null=True, verbose_name='ความเห็น Manager'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='status',
            field=models.CharField(choices=[('pending_manager', 'รอหัวหน้าอนุมัติ (Wait for Manager)'), ('pending_it', 'รอ IT อนุมัติ (Wait for IT)'), ('approved', 'อนุมัติแล้ว (Approved)'), ('rejected', 'ไม่อนุมัติ (Rejected)')], default='pending_manager', max_length=20),
        ),
    ]
