# Generated by Django 5.1.4 on 2026-01-24 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_requests', '0005_accessrequest_it_approval_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='การกระทำ')),
                ('details', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('access_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='access_requests.accessrequest')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ดำเนินการ')),
            ],
        ),
    ]
