# Generated by Django 5.1.4 on 2026-01-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_requests', '0006_accessrequestlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessrequest',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='accessrequest',
            name='name_th',
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='firstname_en',
            field=models.CharField(default='', max_length=150, verbose_name='ชื่อ (อังกฤษ)'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='firstname_th',
            field=models.CharField(default='', max_length=150, verbose_name='ชื่อ (ไทย)'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='lastname_en',
            field=models.CharField(default='', max_length=150, verbose_name='นามสกุล (อังกฤษ)'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='lastname_th',
            field=models.CharField(default='', max_length=150, verbose_name='นามสกุล (ไทย)'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='prefix_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='คำนำหน้า (อังกฤษ)'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='prefix_th',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='คำนำหน้า (ไทย)'),
        ),
    ]
