# Generated by Django 5.1.4 on 2026-01-27 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_requests', '0007_remove_accessrequest_name_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่ปฏิเสธ'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_requests', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ปฏิเสธ'),
        ),
    ]
